# Generated by Django 4.2.26 on 2025-11-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=20, unique=True)),
                ('party_leader', models.CharField(max_length=35)),
            ],
        ),
    ]
