# Generated by Django 4.2.26 on 2025-11-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency_name', models.CharField(max_length=70, unique=True)),
                ('constituency_MP', models.CharField(max_length=50)),
                ('party_holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='community.party')),
            ],
        ),
    ]
